### ISSUE TITLE
Remove uk-link-reset from navbar dropdown menus

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-starter-legumeinfo#11]
As reported is https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/67, the navbar dropdown menus use the `uk-link-reset` class to change the color of the menu links from grey to black. This breaks the hover functionality since the menu items turn black when they're moused over. Remove the `uk-link-reset` class to restore the hover functionality.

**Comment by That-Thing** [comment]
It doesn't seem to be possible to change the text color using UIkit classes without breaking hover or making the text unreadable.

**Comment by sammyjava** [comment]
Yeah I just dropped it on the jekyll-legumeinfo site (use-theme branch, still in PR). I think the default looks pretty good, actually, I don't even remember why I did what I did ages ago.

**Comment by alancleary** [comment]
> It doesn't seem to be possible to change the text color using UIkit classes without breaking hover or making the text unreadable.

Correct. See https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/62; in short, there's too many things people are going to want to customize over time so I'm going to set things up so people can customize whatever they want without my involvement.

**Comment by alancleary** [comment]
> It doesn't seem to be possible to change the text color using UIkit classes without breaking hover or making the text unreadable.

@That-Thing I can't remember if this was your original intent but as of [theme PR #75](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/75) you can customize pretty much anything in UIkit via SCSS in your site.

**Comment by alancleary** [comment]
Done in PR #14.
