### ISSUE TITLE
manifest.json missing

### ISSUE THREAD

**Issue by nathanweeks** [legumeinfo/jekyll-starter-legumeinfo#8]
`bundle exec jekyll build` (tried both in a codespace & locally with `docker compose up`) doesn't appear propagate the manifest.json from the theme to the resulting _site directory.  I'm not sure if that's an issue with the theme or this starter site.

**Comment by alancleary** [comment]
I was unable to replicate this with a fresh copy of the repo using docker compose. Can you provide more details?

**Comment by nathanweeks** [comment]
```
$ git clone --recursive https://github.com/legumeinfo/jekyll-starter-legumeinfo
...
$ cd jekyll-starter-legumeinfo
$ docker compose up
... navigate to http://localhost:4000 in web browser ...
        LiveReload: Browser connected
...
        ERROR `/manifest.json' not found.
.... <CTRL-C>
$ ls -1 _site 
404.html
CODE_OF_CONDUCT.md
LICENSE
README.md
assets
community
contact
download
events
feed.xml
help
index.html
news
taxa
tools
```
The web browser (Chrome) console contains `GET http://localhost:4000/manifest.json 404 (Not Found)`

**Comment by alancleary** [comment]
I'm still not getting the <code>`/manifest.json' not found</code> error, but I am getting the 404. I think this file is a vestige of the fact that I derived the theme from a web app built with UIkit and it isn't actually necessary for our website since it's not a web app. Is there a specific use case you need it for? If not the solution here may be to just remove it.

**Comment by nathanweeks** [comment]
> I'm still not getting the `` `/manifest.json' not found `` error, but I am getting the 404.

To clarify, `ERROR `/manifest.json' not found.` was logged by the `jekyll serve` after a web browser visits http://localhost:4000 and attempts to access /manifest.json. 

> I think this file is a vestige of the fact that I derived the theme from a web app built with UIkit and it isn't actually necessary for our website since it's not a web app. Is there a specific use case you need it for? If not the solution here may be to just remove it.

Thanks for the background info. I don't have a specific use case; if you think it's unnecessary, then it can probably be removed from the theme.

**Comment by alancleary** [comment]
> I don't have a specific use case; if you think it's unnecessary, then it can probably be removed from the theme.

OK, I'll open an issue in the theme to remove it.

**Comment by alancleary** [comment]
Won't fix. See [issue #51](https://github.com/legumeinfo/jekyll-theme-legumeinfo/issues/51) in the theme for details.
